command_timeout = 750

palette = "mine"

[palettes.mine]
limegreen = '#32CD32'

[battery]
disabled = true
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[c]
disabled = true
commands = [["$CC", "--version"], ["clang", "--version"], ["gcc", "--version"]]
format = 'via [$symbol($name( $version)) ]($style)'

[character]
success_symbol = "[➲](limegreen)"
error_symbol = "[✗](bold red)"

[directory]
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[cmd_duration]
disabled = true

[dotnet]
disabled = true

[erlang]
symbol = "ⓔ "

[git_branch]
disabled = false

[git_status]
disabled = false

[nodejs]
symbol = "[⬢](bold green) "

[package]
disabled = true

[pulumi]
symbol = "🧊 "

[python]
python_binary = ["py"]
detect_files = []
detect_folders = [".venv"]

[typst]
symbol = "t "
